### ISSUE TITLE
Suitability for Z8S180 or Z80

### ISSUE THREAD

**Issue by feilipu** [notwendig/FreeRTOS-eZ80F91#1]
Willi,

looking at your portable layer, it seems as if this port could be used with a Z80 or Z8S180 with no further work. Perhaps some adjustment of I/O or interrupt locations would be required? What do you think?

You reference the ZDSII Acclaim 5.2.1 Developer Environment as the development platform. I haven't found any definitive reference that this environment supports the Z8S180 on Zilog web site.

Could you let me know your opinion about support for Z8S180, please?
Would you suggest this environment over the SDCC, for example?

Does ZDSII support automatic MMU control for banked functions and / or banked data (far pointers)?

Thanks for any help.
Phillip

**Comment by notwendig** [comment]
Hi Phillip

you are possible right:)

But at least you need one CTC with the native Z80 to trigger the
Scheduler. Then has the Z80 no Vector-Interrupt capabilities. So you
have to demux on interrupt sources or use Mode 2 and additional Hardware
that supports vectors.

I'm not sure if the Acclaim makes sinn to be used on native Z80
projects. And no, MMU are not supported by the Acclaim. OK, the ez80 has
64K paging in Z80 mode, so it could compile native Z80 sources too. And
the output is Intel Hex format, that could possible download to the Z80
target or burned on a eeprom eg. But I would use a clear Z80 developer
environment from the good old times of that Z80 MPU :)

About the Z8S180. That MPU has all you need to get the FreeRTOS port
running on. But it could be a hard job to bring Ethernet to those
platforms :)

My next challenge (after all hardware is supported) is to get FreeRTOS
running on mixed mode and to add Z80 Tasks (CP/M 2.2 for example). Than
my ez80f91 board can replace any real Z80 based PCB without any/many
rework on their Z80 codes.

If that works a EZ80 based PCB can run multiple Z80-Processes in
parallel each isolated on their own 64K Partition.

About SDCC. That's a great open source environment. If it would be able
to support my target debugger, I would give it a try. This days I'm
working on a solution to get ZiLOG's USBSmartCable running under LINUX.
For that I need a good description about NEXUS API and the protocol used
between the Windows DLL and SmartCable device. Still missing :(

As you can see Phillip there's a lot of work left to be done. Join the
project to realize your ideas, for help and just for fun.

Thanks for your interest
Jürgen Willi

Am 31.05.2016 um 04:27 schrieb Phillip Stevens:

**Comment by feilipu** [comment]
Hi Jürgen Willi,

Thank you. I am very happy to join the Z180 FreeRTOS project. I didn't know there was such a thing, but very happy to be part of it.

I've been looking after a [FreeRTOS for AVR ATmega](https://sourceforge.net/projects/avrfreertos/) devices now for about 6 years, and it has been downloaded about 20,000 times since 2011. More recently a lot of people from the Arduino community have had interest in [Arduino FreeRTOS](https://create.arduino.cc/projecthub/feilipu/using-freertos-multi-tasking-in-arduino-ebc3cc). So I have some experiences with FreeRTOS to support the effort.

What I'm keen to do is to try to build a computer that is embedded (doesn't change its code once booted) and is based on Z80 family as a platform. I have only a little experience with hardware from the [AVR ATmega](ickstarter.com/projects/feilipu/goldilocks-analogue-classic-arduino-audio-superpow) side, but now I want to build something as a memorial for the 40th year of the Z80, that can work in this day and age, with eg. Eth, I2C, and USB.

I've [done some thinking](https://feilipu.me/2016/05/23/another-z80-project/), and I will select a Z8S180 as the core of the project. It is not too advanced (like the eZ80, so as to be just another flavour embedded device, like the ATmega), and not too basic (like the Z80, so as to make running a RTOS difficult because the lack of integrated timers for SysTick for example).

I've built a RC2014 kit, which should help get me on the right path for creating a C development environment, but it won't help with FreeRTOS development (no timers, etc). Hence my questions about support, because I don't necessarily want to start off on the wrong track.

It seems there are only a few tools available to support Banked and Common 1 MMU modes for .text sections in C. The Softools compiler is one that supports MMU paging, but it is ages old and still costs $400. Other references I've found have disappeared off the Internet.

I don't have too much time available, so my development process is very slow, compared to someone who can do development as a professional activity. But anyway, happy to help where I can.

Phillip

**Comment by notwendig** [comment]
Hi Phillip


Am 31.05.2016 um 14:03 schrieb Phillip Stevens:
>
> Hi Jürgen Willi,
>
> Thank you. I am very happy to join the Z180 FreeRTOS project. I didn't
> know there was such a thing, but very happy to be part of it.
>
Never mind, feel welcome. I don't know if there is already existing an
Z180 FreeRTOS project. Hence, we can make a branch to create on :)

> I've been looking after a FreeRTOS for AVR ATmega
> <https://sourceforge.net/projects/avrfreertos/> devices now for about
> 6 years, and it has been downloaded about 20,000 times since 2011.
>
Oh, on my last professional project I have used a AT90CAN on an
distributed System.


> More recently a lot of people from the Arduino community have had
> interest in Arduino FreeRTOS
> <https://create.arduino.cc/projecthub/feilipu/using-freertos-multi-tasking-in-arduino-ebc3cc>.
> So I have some experiences with FreeRTOS to support the effort.
>
> What I'm keen to do is to try to build a computer that is embedded
> (doesn't change its code once booted) and is based on Z80 family as a
> platform. I have only a little experience with hardware from the AVR
> ATmega
> <ickstarter.com/projects/feilipu/goldilocks-analogue-classic-arduino-audio-superpow>
> side, but now I want to build something as a memorial for the 40th
> year of the Z80, that can work in this day and age, with eg. Eth, I2C,
> and USB.
>
Yes, a good decision because Z80 based Systems are easily to build.
Don't forget to add some essential additional hardware. For a native Z80
system at least it should support one CTC a SIO and possible two PIOs.
For SPI and or I2C there is a lot of standard chips that can be added
without any circumstances. If you plan to use SD Cards they are
necessary. All included on the Z8S180??
>
> I've done some thinking
> <https://feilipu.me/2016/05/23/another-z80-project/>, and I will
> select a Z8S180 as the core of the project. It is not too advanced
> (like the eZ80, so as to be just another flavour embedded device, like
> the ATmega), and not too basic (like the Z80, so as to make running a
> RTOS difficult because the lack of integrated timers for SysTick for
> example).
>
I've never seen this "Homebrew Z80 Computer Kit" but on the internet I
could see it is a modular and highly expandable system. I'm sure there
is a CTC module to drive a scheduler. At least you can add something
like a multivibrator to interrupt the Z80 cyclically.
>
> I've built a RC2014 kit, which should help get me on the right path
> for creating a C development environment, but it won't help with
> FreeRTOS development (no timers, etc). Hence my questions about
> support, because I don't necessarily want to start off on the wrong track.
>
That should not be the problem. But to setup a powerful environment to
develop and debug on C/ASM source level is one essential part. I
preferring JTAG for debug and download.
>
> It seems there are only a few tools available to support Banked and
> Common 1 MMU modes for .text sections in C. The Softools compiler is
> one that supports MMU paging, but it is ages old and still costs $400.
> Other references I've found have disappeared off the Internet.
>
For small projekt paging and banking can be developed by hand. Is not to
much. It always depends strong on the used MMU. Compiler can only help
to manage the partitions to prevent infinit switchen or death-locks on
pages. Hence, most things you have to do by a good firmware design.
>
> I don't have too much time available, so my development process is
> very slow, compared to someone who can do development as a
> professional activity. But anyway, happy to help where I can.
>
Me too. But nobody drives us :)
If you would like to become a member on the Ez80f91 FreeDOS guthub
projekt, tell my and I connect you. Then you can work an a branch like
me and we have to integrate our stuff from time to time on the main branch.
Greetings
Jürgen

PS: Don't get worry about my worst english. Its not my native language
and I'm a absolute fool to learn other languages :) Don't hesitate to
ask or to correct me.

**Comment by feilipu** [comment]
Jürgen,

please invite me to your project eZ80F91.
I would like to work specifically on a Z8S180 branch.

It may take me some time (even 6 months) to build appropriate Z180 hardware to test on.
I intend to call my hardware [YAZ180](https://feilipu.me/?s=YAZ180), and my blog will always contain the latest episode of the development story.

But, in the interim I will begin experimenting with the [RC2014 ](rc2014.co.uk)Z80 platform, knowing well that it can't run FreeRTOS (no Timer Interrupts).

I have asked the Softools people whether they can provide a "non-commercial" or "hobby" licence for their [SASM C Compiler](http://www.softools.com/scz180.htm). This SASM C Compiler fully supports Z180 bank switching for .text Sections (in Banked), but priced at US$415 it is not acceptable for my purpose.

But if I don't get an good answer I will use the following platform. [Z88 Development Kit](http://www.z88dk.org/wiki/doku.php) with the [SDCC C Compiler](http://sdcc.sourceforge.net/). Based on my limited reading, it seems that this will provide an optimised set of standard C libraries (assembler), and use the better supported SDCC compiler. But still, control of the MMU still seems to be a manual process under SDCC.

Ubrigens, wegen deinen Englisch koennen. Keine Ursache.

Gruesse, Phillip

**Comment by notwendig** [comment]
Hi Phillip

nice project you are worked on :)

Do you know about YAZE? A nice Z80 emulator. The reason I ask is you
called your project YAZ180 :)

I did developed a Z80 emulation too started at the early 90th.  I added
some Projekt to the bundel from time to time. See
https://sourceforge.net/projects/zilogz80/ if you like to test it:)

By the way. Wellcome to the FreeRTOS port. I would have you added
already but I do not know which account I should use. I found two
accounts possible assigned to you on guthub. Tell me which account  I
should use.

Send it by a DM on twitter, because we are following each other.

Regards

Jürgen



Am 01.06.2016 um 02:51 schrieb Phillip Stevens:
